eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 8083
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/farling?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
  redis:
    host: localhost
    port: 6379
env: dev
